//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace gysv2.Models
{
    
    
    public class G_Admin
    {
        
        [Property(PType="PK", Model=3)]
        public int ID
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string UserCode
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string PassWord
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string UserName
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string Sex
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string Tel
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string Email
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string Dep
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string Com
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string Remark
        {
            get
            ;
            set
            ;
        }
    }
}
