//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace gysv2.Models
{
    
    
    public class G_Division
    {
        
        [Property(Model=3)]
        public int cComCode
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cCompName
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cServer
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cUser
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cPassWord
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cAcc
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string iYear
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cInterface
        {
            get
            ;
            set
            ;
        }
    }
}
