//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace gysv2.Models
{
    
    
    // Author:林炜 
    // {
    //  "Name": "State",
    //  "type": "String",
    //  "Tag": {}
    //}
    public class G_KKmanger_info
    {
        
        [Property(PType="PK", Model=3)]
        public int ID
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string Type
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string VendorCode
        {
            get
            ;
            set
            ;
        }
        
        [Property(Model=3)]
        public decimal Price
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string Reason
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public System.DateTime G_date
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string G_name
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public System.DateTime S_date
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string S_name
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public System.DateTime D_date
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string D_name
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public System.DateTime Q_date
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string Q_name
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public System.DateTime J_date
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string J_name
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string TypeID
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string VendorName
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cDefine3
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cDefine4
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cDefine5
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string text
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string State_text
        {
            get
            ;
            set
            ;
        }
    }
}
