//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace gysv2.Models
{
    
    
    // Author:林炜 
    // {
    //  "Name": "State",
    //  "type": "String",
    //  "Tag": {}
    //}
    public class G_ListInfo
    {
        
        [Property(PType="PK", Model=3)]
        public int ID
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string LIFNR
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string BELNR
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string BUZEI
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public System.DateTime BUDATE
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string NAME1
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string EBELN
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string EBELP
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string MATNR
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string MAKTX
        {
            get
            ;
            set
            ;
        }
        
        [Property(Model=3)]
        public decimal MENGE
        {
            get
            ;
            set
            ;
        }
        
        [Property(Model=3)]
        public decimal WRBTR
        {
            get
            ;
            set
            ;
        }
        
        [Property(Model=3)]
        public decimal JSJE
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string MEINS
        {
            get
            ;
            set
            ;
        }
        
        [Property(Model=3)]
        public decimal RATE
        {
            get
            ;
            set
            ;
        }
        
        [Property(Model=3)]
        public decimal KLQE
        {
            get
            ;
            set
            ;
        }
        
        [Property(Model=3)]
        public decimal MRBHQE
        {
            get
            ;
            set
            ;
        }
        
        [Property(Model=3)]
        public decimal MRSQ
        {
            get
            ;
            set
            ;
        }
        
        [Property(Model=3)]
        public decimal SJBQE
        {
            get
            ;
            set
            ;
        }
        
        [Property(Model=3)]
        public decimal SJSJ
        {
            get
            ;
            set
            ;
        }
        
        [Property(Model=3)]
        public decimal SJHQE
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string WAERS
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public System.DateTime GCDAT
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public System.DateTime JXDAT
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string ZTERM
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string TEXT
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string MWSKZ
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string FLAG
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string YSFPH
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string Invoice_id
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string GJAHR
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string MBLNR
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string MJAHR
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string BELNR1
        {
            get
            ;
            set
            ;
        }
        
        [Property(Model=3)]
        public decimal Old_JSJE
        {
            get
            ;
            set
            ;
        }
        
        [Property(Model=3)]
        public decimal Old_KLQE
        {
            get
            ;
            set
            ;
        }
        
        [Property(Model=3)]
        public decimal Old_MRBHQE
        {
            get
            ;
            set
            ;
        }
        
        [Property(Model=3)]
        public decimal Old_MRSQ
        {
            get
            ;
            set
            ;
        }
        
        [Property(Model=3)]
        public decimal Old_SJBQE
        {
            get
            ;
            set
            ;
        }
        
        [Property(Model=3)]
        public decimal Old_SJSJ
        {
            get
            ;
            set
            ;
        }
        
        [Property(Model=3)]
        public decimal Old_SJHQE
        {
            get
            ;
            set
            ;
        }
        
        [Property(Model=3)]
        public decimal Old_WRBTR
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string ZBELNR
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string RBLGP
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public System.DateTime Date
        {
            get
            ;
            set
            ;
        }
    }
}
