//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace gysv2.Models
{
    
    
    public class G_Order
    {
        
        [Property(PType="PK", Model=3)]
        public int ID
        {
            get
            ;
            set
            ;
        }
        
        [Property(Model=3)]
        public int S_ID
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string PPCIds
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string PPDesc
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cVencode
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cVenName
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cComCode
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cState
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cDepCode
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cDepaName
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cPersonName
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public System.DateTime cPoCode
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cMemo
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cDefine1
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cDefine2
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cDefine3
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cDefine4
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cDefine5
        {
            get
            ;
            set
            ;
        }
    }
}
