//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace gysv2.Models
{
    
    
    public class G_Plan_s1
    {
        
        [Property(PType="PK", Model=3)]
        public int ID
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cNo
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string PPDesc
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public System.DateTime cDate
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cComCode
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cMonth
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cMonthOne
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cMonthTwo
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cMonthThree
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cMonthFour
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cMonthFive
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cPersonNo
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cPerson
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cMemo
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cDefine1
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cDefine2
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cDefine3
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cDefine4
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cDefine5
        {
            get
            ;
            set
            ;
        }
        
        [Property(Model=3)]
        public int IDs
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string sNo1
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string sNo2
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string sName
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string sIsPrm
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string sInvStd
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string sIsSfm
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string sPersonNo
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string sVendorNo
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string sPerson
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string sVendor
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string sProportion
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string sMonthOne
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string sMonthTwo
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string sMonthThree
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string sMonthFive
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string sMonthFour
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string sMemo
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string sDefine1
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string sDefine2
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string sDefine3
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string sDefine5
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string sDefine4
        {
            get
            ;
            set
            ;
        }
        
        [Property(Model=3)]
        public int s_ID
        {
            get
            ;
            set
            ;
        }
    }
}
