//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace gysv2.Models
{
    
    
    public class G_QualityReadTime
    {
        
        [Property(PType="PK", Model=3)]
        public int ID
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string NewID
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string VenID
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string ReadTime
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cDefine1
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cDefine2
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cDefine3
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cDefine4
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cDefine5
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cDefine6
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cDefine7
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cDefine8
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cDefine9
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cDefine10
        {
            get
            ;
            set
            ;
        }
    }
}
