//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace gysv2.Models
{
    
    
    // Author:林炜 
    // {
    //  "Name": "State",
    //  "type": "String",
    //  "Tag": {}
    //}
    public class G_RKmanger
    {
        
        [Property(PType="PK", Model=3)]
        public int ID
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string Vencode
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string Rk_id
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public System.DateTime G_date
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string G_name
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public System.DateTime J_date
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string J_name
        {
            get
            ;
            set
            ;
        }
    }
}
