//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace gysv2.Models
{
    
    
    // Author:林炜 
    // {
    //  "Name": "State",
    //  "type": "String",
    //  "Tag": {}
    //}
    public class G_Status_qs
    {
        
        [Property()]
        public string S_id
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string H_id
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string G_date
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string Vencode
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string Matnr
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string Matbr_matkx
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string Bstmg
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string Jshsj
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string Jshsje
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string Person
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string date
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string E_date
        {
            get
            ;
            set
            ;
        }
    }
}
