//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace gysv2.Models
{
    
    
    // Author:林炜 
    // {
    //  "Name": "State",
    //  "type": "String",
    //  "Tag": {}
    //}
    public class G_Status
    {
        
        [Property()]
        public string S_id
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string H_id
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string G_date
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public System.DateTime GZ_date
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string Vencode
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string Matnr
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string Matbr_matkx
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string Bstmg
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string Jshsj
        {
            get
            ;
            set
            ;
        }
        
        [Property(Model=3)]
        public decimal Jshsje
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string Person
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string Mw
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string Invoice_id
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string date
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string E_date
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string Mark
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string KBETR
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cDefine2
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cDefine3
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cDefine4
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cDefine5
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cUserName
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string Sh_Person
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string newKBETR
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string newJshsj
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string newJshsje
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string Update
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cDefine6
        {
            get
            ;
            set
            ;
        }
    }
}
