//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace gysv2.Models
{
    
    
    public class G_VmiInfo
    {
        
        [Property()]
        public string MBLNR
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string ZEILE
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string MATNR
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string BWART
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string MENGE
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string BUDAT
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string SHKZG
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string MAKTX
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string VenCode
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cDefine1
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cDefine2
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cDefine3
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cDefine4
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cDefine5
        {
            get
            ;
            set
            ;
        }
    }
}
