//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace gysv2.Models
{
    
    
    public class G_AnswerInfo
    {
        
        [Property(PType="PK", Model=3)]
        public int id
        {
            get
            ;
            set
            ;
        }
        
        [Property(Model=3)]
        public int Q_id
        {
            get
            ;
            set
            ;
        }
        
        [Property(Model=3)]
        public int H_id
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string Text
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public System.DateTime Date
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string Name
        {
            get
            ;
            set
            ;
        }
    }
}
