//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace gysv2.Models
{
    
    
    public class G_KKtype
    {
        
        [Property(PType="PK", Model=3)]
        public int ID
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string type
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string G_date
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string G_name
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public System.DateTime S_date
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string S_name
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public System.DateTime D_date
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string D_name
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string D_state
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cDefine1
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cDefine2
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cDefine3
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cDefine4
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cDefine5
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cDefine6
        {
            get
            ;
            set
            ;
        }
    }
}
