//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace gysv2.Models
{
    
    
    // Author:林炜
    public class G_News
    {
        
        [Property(PType="PK", Model=3)]
        public int ID
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string Title
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string Contents
        {
            get
            ;
            set
            ;
        }
        
        [Property(Model=3)]
        public int TypeID
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string ImageUrl
        {
            get
            ;
            set
            ;
        }
        
        [Property(Model=3)]
        public int Hits
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public System.DateTime EditDate
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string UserID
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string GID
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string FileLoad
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string CompanyID
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cDefine1
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cDefine2
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cDefine3
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cDefine4
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cDefine5
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cDefine6
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cDefine7
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cDefine8
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cDefine9
        {
            get
            ;
            set
            ;
        }
    }
}
