//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace gysv2.Models
{
    
    
    public class G_Order_s
    {
        
        [Property(PType="PK", Model=3)]
        public int ID
        {
            get
            ;
            set
            ;
        }
        
        [Property(Model=3)]
        public int SID
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string PPCIds
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string PPDesc
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cVencode
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cVenName
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cComCode
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cState
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cDepCode
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cDepaName
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cPersonName
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public System.DateTime cPoCode
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cMemo
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cDefine1
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cDefine2
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cDefine3
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cDefine4
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cDefine5
        {
            get
            ;
            set
            ;
        }
        
        [Property(Model=3)]
        public int s_ID
        {
            get
            ;
            set
            ;
        }
        
        [Property(Model=3)]
        public int s_FID
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string s_cInvCode
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string s_cInvName
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string s_cInvStd
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string s_cUnit
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string s_cState
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string s_iQuantiry
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string s_iPrice
        {
            get
            ;
            set
            ;
        }
        
        [Property(Model=3)]
        public int s_iReceivedQTY
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public System.DateTime s_dSDate
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public System.DateTime s_dEDate
        {
            get
            ;
            set
            ;
        }
        
        [Property(Model=3)]
        public int s_iConfirm
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public System.DateTime s_dCDate
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string s_cMemo
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string s_cDefine1
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string s_cDefine2
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string s_cDefine3
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string s_cDefine4
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string s_cDefine5
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string s_cStateName
        {
            get
            ;
            set
            ;
        }
    }
}
