//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace gysv2.Models
{
    
    
    public class G_PersonLimitView
    {
        
        [Property(PType="PK", Model=3)]
        public int ID
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string pUserCode1
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string pUserRole1
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string pUserName1
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string pCompany1
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string pUserCode2
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string pUserRole2
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string pUserName2
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string pCompany2
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cState
        {
            get
            ;
            set
            ;
        }
    }
}
