//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace gysv2.Models
{
    
    
    public class G_PersonLimit
    {
        
        [Property(PType="PK", Model=3)]
        public int ID
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string pUserCode1
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string pUserRole1
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string pUserCompany1
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string pUserCode2
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string pUserRole2
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string pUserCompany2
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public System.DateTime pDate
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string pMemo
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string pDefine1
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string pDefine2
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string pDefine3
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string pDefine4
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string pDefine5
        {
            get
            ;
            set
            ;
        }
    }
}
