//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace gysv2.Models
{
    
    
    public class G_Plans1
    {
        
        [Property(PType="PK", Model=3)]
        public int ID
        {
            get
            ;
            set
            ;
        }
        
        [Property(Model=3)]
        public int IDs
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string sNo1
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string sNo2
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string sName
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string sInvStd
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string sIsPrm
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string sIsSfm
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string sPersonNo
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string sPerson
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string sVendorNo
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string sVendor
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string sProportion
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string sMonthOne
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string sMonthTwo
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string sMonthThree
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string sMonthFour
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string sMonthFive
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string sMemo
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string sDefine1
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string sDefine2
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string sDefine3
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string sDefine4
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string sDefine5
        {
            get
            ;
            set
            ;
        }
    }
}
