//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace gysv2.Models
{
    
    
    // Author:林炜 
    // {
    //  "Name": "State",
    //  "type": "Int32",
    //  "Tag": {
    //    "Model": 3
    //  }
    //}
    public class G_Quality
    {
        
        [Property(PType="PK", Model=3)]
        public int ID
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string Title
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string Contents
        {
            get
            ;
            set
            ;
        }
        
        [Property(Model=3)]
        public int TypeID
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string ImageUrl
        {
            get
            ;
            set
            ;
        }
        
        [Property(Model=3)]
        public int Hits
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public System.DateTime EditDate
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public System.DateTime OpenDate
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string UserID
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string GID
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string FileLoad
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string CompanyID
        {
            get
            ;
            set
            ;
        }
        
        [Property(Model=3)]
        public int SureState
        {
            get
            ;
            set
            ;
        }
    }
}
