//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace gysv2.Models
{
    
    
    public class G_Status_temp
    {
        
        [Property()]
        public string MATNR
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string MAKTX
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string All_Count
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string Dang_Count
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string Duog_Count
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string Dangfl_Count
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string Duogfl_Count
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string Date
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cDefine2
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string Lunt_Count
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string Luntfl_Count
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cDefine5
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string CY_Count
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string CYfl_Count
        {
            get
            ;
            set
            ;
        }
    }
}
