//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace gysv2.Models
{
    
    
    public class G_UserLog
    {
        
        [Property(Model=3)]
        public int LogID
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public System.DateTime LogTime
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string LogType
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string UserName
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string ClientIP
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string PageUrl
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string LogNote
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cUserName
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string RoleName
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string RoleID
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cRole
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cUserCode
        {
            get
            ;
            set
            ;
        }
    }
}
