//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace gysv2.Models
{
    
    
    public class G_UserMView
    {
        
        [Property(PType="PK", Model=3)]
        public int ID
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cUserCode
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cUserName
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cPassWord
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cCompany
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cDepartment
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cRole
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cPersonLimit
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cVendorLimit
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cMobile
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cState
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public System.DateTime cDate
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cMemo
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cDefine1
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cDefine2
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cDefine3
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cDefine4
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cDefine5
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string u_StateName
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string RoleName
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cCompName
        {
            get
            ;
            set
            ;
        }
    }
}
