//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace gysv2.Models
{
    
    
    public class Lw_LogInfo
    {
        
        [Property(PType="PK", Model=3)]
        public int ID
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string TypeName
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string Contents
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public DateTime DateTime1
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string UserCode
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string LogType
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string DID
        {
            get
            ;
            set
            ;
        }
        
        [Property(Model=3)]
        public int DetId
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public DateTime Datetime
        {
            get
            ;
            set
            ;
        }
    }
}
