//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace gysv2.Models
{
    
    
    public class Lw_Site_Roles
    {
        
        [Property(PType="PK", Model=3)]
        public int ID
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string title
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string UrlKey
        {
            get
            ;
            set
            ;
        }
        
        [Property(Model=3)]
        public int parentId
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string isOpt
        {
            get
            ;
            set
            ;
        }
        
        [Property(Model=3)]
        public int cOrder
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string isMenu
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cComponey
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string isAuth
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string isSubMenu
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string isMobile
        {
            get
            ;
            set
            ;
        }
    }
}
