//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace gysv2.Models
{


    // Author:林炜 
    public class Lw_V_News
    {

        [Property(PType = "PK", Model = 3)]
        public int ID
        {
            get
            ;
            set
            ;
        }

        [Property(Model = 1)]
        public string Title
        {
            get
            ;
            set
            ;
        }

        [Property()]
        public string Contents
        {
            get
            ;
            set
            ;
        }

        [Property(Model = 0)]
        public int TypeID
        {
            get
            ;
            set
            ;
        }

        [Property()]
        public string ImageUrl
        {
            get
            ;
            set
            ;
        }

        [Property(Model = 3)]
        public int Hits
        {
            get
            ;
            set
            ;
        }

        [Property()]
        public System.DateTime EditDate
        {
            get
            ;
            set
            ;
        }

        public string EditDate0 { get; set; }

        public string EditDate1 { get; set; }

        [Property(Model = 3)]
        public int UserID
        {
            get
            ;
            set
            ;
        }

        public int State
        {
            get;
            set;
        }

        [Property()]
        public string GID
        {
            get
            ;
            set
            ;
        }

        [Property()]
        public string FileLoad
        {
            get
            ;
            set
            ;
        }

        [Property()]
        public string CompanyID
        {
            get
            ;
            set
            ;
        }
        [Property(Model = 1)]
        public string UserName
        {
            get;
            set;
        }

    }
}
