//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace gysv2.Models
{
    
    
    public class PO_PoDetailsSub
    {
        
        [Property(Model=3)]
        public int AutoID
        {
            get
            ;
            set
            ;
        }
        
        [Property(PType="PK", Model=3)]
        public int ID
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cInvCode
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string dDate
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cMemo
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cDefine
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string iNum
        {
            get
            ;
            set
            ;
        }
        
        [Property(Model=3)]
        public int sID
        {
            get
            ;
            set
            ;
        }
        
        [Property()]
        public string cComCode
        {
            get
            ;
            set
            ;
        }
    }
}
